export const REPOSITORY_TOKENS = {
  PATIENTS: 'PATIENTS_REPOSITORY',
  APPOINTMENTS: 'APPOINTMENTS_REPOSITORY',
  USERS: 'USER_REPOSITORY',
  REFRESH_TOKENS: 'REFRESH_TOKENS_REPOSITORY',
  HEALTH_ALERTS: 'HEALTH_ALERTS_REPOSITORY',
} as const;
